// <auto-generated />
namespace uLearn.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class trashmigr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trashmigr));
        
        string IMigrationMetadata.Id
        {
            get { return "201502241126313_trash migr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
